### ISSUE TITLE
get_sites: var_src

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#100]
change get_sites to accept a true var_src and turn it into a ts_name internally.

**Comment by jread-usgs** [comment]
@aappling-usgs I can take this one

**Comment by jread-usgs** [comment]
actually, you sure we need this?

**Comment by aappling-usgs** [comment]
not a huge deal. i think a true var_src or a different arg name would be appropriate, but don't care much.

**Comment by jread-usgs** [comment]
OK, I was thinking that since get_sites was a lower level (and internal) function, it wouldn't have helpers in it to convert. Instead, it would use the exact type matching. The helpers are in `list_sites` now

**Comment by aappling-usgs** [comment]
that makes sense.
