### ISSUE TITLE
find_site_coords doesn't fail with a bad site

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#133]
```R
site_location("11126000asdf")
     site_name  lat  lon
U              degN degE
1 11126000asdf   NA   NA
```
didn't think this was/is desired functionality. Pretty minor error though

**Comment by aappling-usgs** [comment]
fair enough.  agree that it'd be nice to be told when a site isn't even listed in the metadata table

**Comment by aappling-usgs** [comment]
this appears to also apply to powstreams::get_site_info
