### ISSUE TITLE
add sb_id to metadata table

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#139]
maybe keep in an inventory table that we know needs updating whenever the SB structure changes

**Comment by aappling-usgs** [comment]
this is done. i put it in meta_basic because i decided that whole file is pretty easy to re-compute quickly. it's called sciencebase_id. @jread-usgs, you can format it using something like this:
```r
paste0("https://www.sciencebase.gov/catalog/folder/", get_meta()[3,'sciencebase_id'])
```

**Comment by jread-usgs** [comment]
perfect! thanks
