### ISSUE TITLE
include "O2" in units

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#154]
DO.obs, DO.sat, GPP, etc. - would make mda.streams more compatible with streamMetabolizer. Will require revising & reposting the relevant time series

**Comment by jread-usgs** [comment]
`waffle` is back!

**Comment by aappling-usgs** [comment]
yeah, we'll see. i'd started copying github issues over to trello just so i
could sort them, which is silly & is basically what waffle does. but i
don't love how waffle combines projects, and i'm now working on 4? 5? repos
at once, so this may not be the full solution.

On Tue, Sep 8, 2015 at 8:59 PM, Jordan S Read <notifications@github.com>
wrote:

> waffle is back!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/mda.streams/issues/154#issuecomment-138753024>.
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927
