### ISSUE TITLE
config_to_data: pred and pred_file have truncated local.time values

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#166]
Because we're saving data (including sitetime) as .tsv, we're saving datetimes as character strings accurate to the nearest second. The actual, calculated sitetime values are slightly different from round seconds. Consequently, data fed to models has the rounded local.time values. Consequently, when we get predictions back from a model and try to convert those back to UTC, we get not-exactly-rounded DateTime values. Consequently, predictions (e.g., doobs) merge poorly with other time series inputs in combine_ts, leading to config_to_data outputs like this one:
```r
            local.time   DO.obs   DO.sat depth temp.water          light
U                       mg L^-1  mg L^-1     m       degC umol m^-2 s^-1
4                 <NA> 7.200000       NA   0.2         NA             NA
5  2012-05-14 22:58:49       NA 8.306875   0.2       22.1              0
6                 <NA> 7.034863       NA   0.2         NA             NA
7  2012-05-14 23:28:49       NA 8.355250   0.2       21.8              0
8                 <NA> 6.987796       NA   0.2         NA             NA
9  2012-05-14 23:58:49       NA 8.404128   0.2       21.5              0
10                <NA> 6.990015       NA   0.2         NA             NA
11 2012-05-15 00:28:49       NA 8.453516   0.2       21.2              0
12                <NA> 7.013139       NA   0.2         NA             NA
13 2012-05-15 00:58:49       NA 8.503424   0.2       20.9              0
```
Possible solutions:
* Could it be that rounding to the nearest second after `convert_solartime_to_GMT(local.time,lon,'mean')` always gets us the proper DateTime? That would be nice.
* Maybe we need to download the sitetime or sitetimedaily time series to get the proper, character-based matchup between date stamps. This would be a little slower and would require that sitetime contains all of the desired date stamps, but that should usually (always?) be the case.
* We could try to store sitetime with more precision. This sounds like a pain.

It might make sense to add a check for NAs in local.time in streamMetabolizer::mm_validate_data to help catch problems in whatever solution is implemented.

**Comment by jread-usgs** [comment]
Is our decision to store on SB as tsv (instead or rdata or something else) something that needs to be revisited? Curious what the effort on the various options would be, but rda would help us in a number of ways, this being one of them.

**Comment by aappling-usgs** [comment]
https://github.com/aappling-usgs/mda.streams/commit/ca4738ee07adb0d7d58df8f5996b931a2d67f67b

**Comment by aappling-usgs** [comment]
Well, rounding didn't work. Now I get doobs ts from type='pred' that look like this:
```r
> doobs=mda.streams:::config_to_data_column(var, type, site, src, optional=(data %in% optional))
> doobs
              DateTime    doobs
U                       mg L^-1
1  2012-05-15 05:30:00 7.200000
2  2012-05-15 05:59:59 7.034863
3  2012-05-15 06:30:00 6.987796
4  2012-05-15 06:59:59 6.990015
5  2012-05-15 07:30:00 7.013139
6  2012-05-15 07:59:59 7.037966
7  2012-05-15 08:30:00 7.071014
8  2012-05-15 08:59:59 7.100425
9  2012-05-15 09:30:00 7.128348
10 2012-05-15 09:59:59 7.155720
11 2012-05-15 10:30:00 7.182951
12 2012-05-15 10:59:59 7.210222
13 2012-05-15 11:30:00 7.237614
14 2012-05-15 11:59:59 7.377654
15 2012-05-15 12:30:00 7.579045
16 2012-05-15 12:59:59 7.801606
17 2012-05-15 13:30:00 8.015841
18 2012-05-15 13:59:59 8.221326
```
It's possible that rounding all of the calculated dates in stage_calc_ts would fix things. But that's a lot of rounding and rewriting, especially if we think we might switch to .RData soon
