### ISSUE TITLE
store data on SB as .RData instead of .tsv?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#167]
Jordan writes in #166 :

> Is our decision to store on SB as tsv (instead or rdata or something else) something that needs to be revisited? Curious what the effort on the various options would be, but rda would help us in a number of ways, this being one of them.

**Comment by aappling-usgs** [comment]
I assume by .rda you mean .RData, right, @jread-usgs ?

Might be worth revisiting, yes. Most external data we acquire have just a few decimal points anyway, so saving them as .tsv is lossless. But in the case of #166 we've generated data - the local.time - and are losing precision when we save it. This could potentially be an issue for any calculated data: solartime, PAR, gpp_estBest/er_estBest/K600_estBest, etc.

Pros of switching:
* Higher precision saved data for above cases
* Smaller files, I think
* Faster to read in data to R
* Switching would be a [mandatory] opportunity to check the status of our full data import pipeline

Tasks involved in switching:
* Rewrite mda.streams::write_ts
* Make sure that all ts production goes through write_ts. This should be the case, but worth checking
* Replace all data on SB with .rda

Cons of switching:
* The time required to alter write_ts & replace all ts data on SB. Could reduce processing time by writing another function to convert .tsv files to .RData for NLDAS data especially, but that requires additional programmer time. Alternatively, we delete, redownload, repost
* Collaborators interested in downloading data would need to be sufficiently R savvy

**Comment by jread-usgs** [comment]
yes, I meant .RData

We probably want to talk about this in person, but we could add a "Download" button to the shiny apps that spits out a tsv or csv for collabs. Just a thought about that hurdle.

**Comment by aappling-usgs** [comment]
If/when we do this, let's also do #154

**Comment by aappling-usgs** [comment]
Added impetus: storing censored data objects on SB will be a lot easier & more complete if we can keep them as qw objects.

**Comment by aappling-usgs** [comment]
per https://github.com/USGS-CIDA/stream_metab_usa/issues/68, let's see if it's reasonable to archive old data versions within the current ts items - we can simply rename them to prefix with the date posted, e.g. "150728_sw_nldas.tsv" or "150728_sw_nldas.Rdata" and keep a copy of the most recent version without a date, e.g., "sw_nldas.RData". 

updates to ts can copy-post/rename the current version to a version with a date tag derived from the posted file information (i think sbtools can tell you when something was posted now). then post the new version without a date tag.

**Comment by jread-usgs** [comment]
I think it makes sense, since we are only storing single objects as binary, to use `.rds` instead of `.RData`. I was looking into this last week and do prefer the workflow for `saveRDS` and `readRDS

**Comment by jread-usgs** [comment]
Looking closer, we do have models as `.RData`, so I can see how it might make sense to keep just a single R binary. Let's discuss?

**Comment by aappling-usgs** [comment]
Didn't see this comment this morning, though we've talked about it. I'm all for `saveRDS` for ts files, and I don't think we need to worry much about whether the models are stored differently because it's all hidden behind a wall of abstraction and stored in different corners of SB.

**Comment by jread-usgs** [comment]
Looks like `post_ts` is not going to let us have multiple files under a `ts` item w/o a bit of a re-write. 

`download_ts` will need a bit of an update to do that too.

Wondering if there are some options for a clean way to do this:

1. do we want to allow multiple files on an item?
2. should we have a different key for archived data?
3. are we going to allow mixed types for files? I.e., archived data as `rds`, current data as `rds` and archived data as `tsv.gz`?

Curious what you think @aappling-usgs

**Comment by aappling-usgs** [comment]
yeah, it's gonna require some work, for sure. thanks for taking it on, @jread-usgs!

1. yes, i want multiple files on an item, unless you can see a good reason to do otherwise. i don't think we'll ever make it past 5 or 10 files, which sciencebase doesn't mind, right? and the mda.streams lookup functions are all tailored to the current item organization.
2. do you mean an SB key? if so, then i think multiple files on the same item would be better and therefore we don't need different keys. we'll need to come up with a file naming scheme, though - something like prefixing with a datestamp as suggested above, but i'm open to anything that makes sense to you
3. mixed types is fine with me as long as `download_ts` and `read_ts` can handle either type. `stage_ts` and `post_ts` should only need to be able to handle the `rds` version going forward.

**Comment by jread-usgs** [comment]
Cool! Going with *1*. Agree with your points and I am sorting it out right now

**Comment by aappling-usgs** [comment]
sounds good!

**Comment by aappling-usgs** [comment]
as added encouragement for this re-pull of the data, here's one site where the data column of the ts is mostly NAs. i bet this is because there were two data columns returned from `dataRetrieval` and we only knew to look for one.
```
wtr <- get_ts('wtr_nwis', 'nwis_06601200')
library(ggplot2); library(unitted)
ggplot(v(wtr), aes(x=DateTime, y=wtr)) + geom_line()
nrow(wtr) # 128707
length(which(!is.na(wtr$wtr))) # 2445
```
![image](https://cloud.githubusercontent.com/assets/12039957/14034940/5ffa2e70-f1f6-11e5-8fde-2d070664026d.png)

**Comment by aappling-usgs** [comment]
And here's another - duplicate time stamp suggesting improper timezone handling:
```r
sw <- get_ts('sw_nldas', 'nwis_06601200')
> sw[1582:1588,]
                DateTime      sw
U                         W m^-2
1582 2006-12-05 16:00:00 239.984
1583 2006-12-05 17:00:00 300.459
1584 2006-12-05 18:00:00 258.681
1585 2006-12-05 18:00:00 258.681
1586 2006-12-05 19:00:00 248.404
1587 2006-12-05 20:00:00 210.166
1588 2006-12-05 21:00:00 172.176
```
