### ISSUE TITLE
stage_custom_site, post_custom_site

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#174]
Functions like `stage_styx_site` and `post_styx_site` that accept a data.frame with standard column names (as var_src), stage the site and corresponding ts data files, and post them.

Immediate application is Bob's French and Spring Creek.

The point of all the more structured stage and post functions is to document something about the data source...think about ways to keep metadata with these custom sites somehow.

**Comment by jread-usgs** [comment]
Does this maybe imply extending the use of SB into streamPULSE? Or exploring it?

**Comment by aappling-usgs** [comment]
I think we're committed to CUAHSI-HIS as the back end for streamPULSE, aren't we? That said, @kwiter may be able to reuse a lot of code if he can rewrite the back end of post_site, post_ts to write to the CUAHSI db instead of ours. I'd hope that the core streamPULSE sites could be handled in a more formal way than "custom", though - they should have their own metadata functions at the very least, and maybe also their own staging and posting functions if there's additional data checking, formatting, or annotating to do.

**Comment by jread-usgs** [comment]
OK, just asking because PC was drawing a line in the sand of USGS data vs non, so the PC data plus the non-PC data would be streamPULSE, no? 
But, I am now thinking this task is probably targeting a good way to get test data into the modeling workflow, not a way to get additional site data into the analysis?

**Comment by aappling-usgs** [comment]
Yes, my purpose is to get two 1-day datasets onto SB to test the models.

**Comment by jread-usgs** [comment]
:+1:
