### ISSUE TITLE
use a github personal access token in appveyor

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#208]
Appveyor fails on this 403 issue with install_github all the time: https://ci.appveyor.com/project/jread-usgs/mda-streams/build/0.1.345#L150. It happens with any package and arises because GitHub limits the number of anonymous requests that come from a single location (e.g., appveyor). I don't know why this doesn't happen on Travis (at least, I haven't seen it there).

I made notes on this in https://github.com/USGS-R/mda.streams/pull/201 as well. In that note I included links to instructions:
* setting a GitHub personal access token: https://help.github.com/articles/creating-an-access-token-for-command-line-use/
* auth_token: http://www.inside-r.org/packages/cran/devtools/docs/install_github
* env var GITHUB_PAT in http://www.inside-r.org/packages/cran/devtools/docs/github_pat

Additional diagnoses + solutions since then:
https://github.com/krlmlr/r-appveyor/issues/33 (hey, @jread-usgs opened this one way back when!) where **masalmon** summarizes:
> * get a personal access token from Github (in Github settings)
> * encrypt the token in appveyor following https://www.appveyor.com/docs/build-configuration#secure-variables
> * in appveyor.yml, add "environment: GITHUB_PAT: secure: "

So now we just need to try it.

**Comment by jread-usgs** [comment]
I wonder why I don't get this issue on `geoknife`? https://ci.appveyor.com/project/jread-usgs/geoknife/history

**Comment by jread-usgs** [comment]
granted, you PR mda.streams quite a bit more. just wondering why I haven't run into it...

**Comment by aappling-usgs** [comment]
Because you don't install packages from github in Appveyor: https://github.com/USGS-R/geoknife/blob/master/appveyor.yml#L11 vs https://github.com/USGS-R/mda.streams/blob/master/appveyor.yml#L19

**Comment by jread-usgs** [comment]
....whoops...yes, that makes total sense.

**Comment by aappling-usgs** [comment]
OK, here I go:
1. Create a [GitHub access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) with no scope boxes checked (default is read-only, which should be plenty)
2. Copy and paste the token into https://ci.appveyor.com/tools/encrypt
3. Copy and paste the encrypted value into appveyor.yml in this project, such that I now have
```r
environment:
  R_CHECK_ARGS: --no-build-vignettes --no-manual --no-multiarch
  R_BUILD_ARGS: --no-build-vignettes --no-manual
  R_INSTALL_ARGS: --no-multiarch
  GITHUB_PAT: secure: encryptedcopypastestringgoeshere
```
(where `R_CHECK_ARGS`, `R_BUILD_ARGS`, and `R_INSTALL_ARGS` were already there for other reasons)
4. Just commit and run, because `install_github` is already looking for a `GITHUB_PAT` environment variable by default.

I'm doing this for my own appveyor account as a trial run, but the main set of appveyor builds happens on Jordan's, so if this works we'll switch the GITHUB_PAT to refer to a token that's encrypted on @jread-usgs's appveyor account.

**Comment by aappling-usgs** [comment]
It worked! But right now it's just working on [my account](https://ci.appveyor.com/project/aappling-usgs/mda-streams/build/1.0.146#L136); @jread-usgs , would you please follow the same steps above for [your version of the project](https://ci.appveyor.com/project/jread-usgs/mda-streams)?
