### ISSUE TITLE
fix stage_nwis_ts use of dataRetrieval

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#221]
from @jread-usgs: `stage_nwis_ts` is ending up with the accepted/provisional code instead of the data:
```
head(site_data)
             DateTime   doobs
U                     mg L^-1
1 2014-01-01 01:00:00       P
2 2014-01-01 01:05:00       P
3 2014-01-01 01:10:00       P
4 2014-01-01 01:15:00       P
5 2014-01-01 01:20:00       P
6 2014-01-01 01:25:00       P
```
this is independent of changing to .rds

```
datacol <- names(nwis_data)[5]
```
this assumption I think is the issue

line 101 of stage_nwis_ts.R

`dataRetrieval::renameNWISColumns` might be helpful here.

**Comment by jread-usgs** [comment]
Fixed in #222 ?
