### ISSUE TITLE
is the new stage_nwis_ts robust against a site with no data?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#225]
Haven't tested, but I fear it will not fail gracefully. check this against a known empty against >= v0.9.1

**Comment by aappling-usgs** [comment]
it is now. i ran into issues and fixed them.
```r
> stage_nwis_ts(c('nwis_04024315','nwis_04024430'), var='doobs', times=c('2014-01-01','2014-01-03'))
NULL
```

https://github.com/USGS-R/mda.streams/commit/af61ca94f1ea6c955806783fd85420665a94bacf
