### ISSUE TITLE
separate out archive_ts_file from post_ts

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#228]
so, it sounds like we want to be able to systematically archive a bunch of files with the old extensions w/o actually replacing w/ a new file. 

Let's separate this part out into a new function and have the part of post_ts that would use it, call it.

**Comment by aappling-usgs** [comment]
also, it would be nice to be able to combine archive=T/F with on_exists=replace/merge. a separate function would permit that
