### ISSUE TITLE
create stage_gldas_ts (or change to stage_ldas_ts and handle both)?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#269]
`stage_nldas_ts` is specific to NLDAS right now, but a lot will apply to `GLDAS`. either share these or create a separate function for GLDAS

**Comment by jread-usgs** [comment]
@aappling-usgs do you know all that relies on `stage_nldas_ts`? is it just the remake in `stream_metab_usa`?

**Comment by aappling-usgs** [comment]
that's all i see in mda.streams, and that's all there should be in stream_metab_usa. yes, i think the remake is the only thing that depends on `stage_nldas_ts`

**Comment by aappling-usgs** [comment]
we now have `stage_ldas_ts` that does both.
