### ISSUE TITLE
Title is inconsistent for post_watershed()

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#32]
really odd...looping through and subsetting shapefiles, and the title is different on two sequential posts:

```R
query_item_identifier(scheme='mda_streams',type='watershed')
           title                       id
1  nwis_01018035 54b48ec9e4b0d971394a866b
NA     watershed 54b48ef9e4b0d971394a8686
```

**Comment by jread-usgs** [comment]
ahh...I am guessing this is because the first item had siblings, the second didn't ('watershed')

**Comment by jread-usgs** [comment]
this might be because there is a `item_upload_create` in sbtools, but not a upload/append item function. So it seems the behavior is different if the parent already has files associated with it?

**Comment by jread-usgs** [comment]
Scratch that theory. Seems to almost be random. `query_item_identifier(scheme='mda_streams',type='watershed', limit=200)`

**Comment by jread-usgs** [comment]
looks like this is sometimes silently failing: 
https://github.com/USGS-R/mda.streams/blob/master/R/post_watershed.R#L40

**Comment by aappling-usgs** [comment]
this is a year old and probably won't be relevant if/when we get back to pulling watershed files.
