### ISSUE TITLE
file for variables

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#39]
such as scheme ('mda_streams')

**Comment by lawinslow** [comment]
I was just thinking you could code it as a package global

**Comment by jread-usgs** [comment]
Still need a script/file for it, right?

**Comment by lawinslow** [comment]
Yeah, often in an AAA.R file

**Comment by jread-usgs** [comment]
ok, so your disagreement with "file for variables" ...was...what?

**Comment by lawinslow** [comment]
none, apparently interpreted it poorly

**Comment by jread-usgs** [comment]
plotttly

**Comment by aappling-usgs** [comment]
i believe this is called `mda.streams:::pkg.env` now - that's what holds scheme. we also have `get_var_codes()` and `get_ts_variables()` which report on available variables.
