### ISSUE TITLE
speed up read_ts

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#44]
this is currently read.table. Is pretty slow (seems slower than the file download) and could be sped up by avoiding read.table. Something in `tom` eventually?

**Comment by lawinslow** [comment]
Just to clarify, you mean `read.table` from the file system is taking more time than `download.file`?

**Comment by jread-usgs** [comment]
yeah, haven't provided it, but seems to be the case. They are close. can do both in sequence:
```r
file_handle <- download_ts(site = 'nwis_01408500', variable = 'doobs')
dissolved_oxygen <- read_ts(file_handle)
```

**Comment by lawinslow** [comment]
Slow step is most likely this line
```{r}
df[, 1] <- as.POSIXct(df[, 1])
````
for a well formatted file, there aren't much faster options than `read.table` so tom is unlikely to improve the situation. May want to check where the bottleneck really is and maybe look into the fasttime package.,

**Comment by jread-usgs** [comment]
Odd, I always thought read.table was slower than alternatives. Got any sources to back up your claim? data.table has some zip to the fread: http://stackoverflow.com/questions/1727772/quickly-reading-very-large-tables-as-dataframes-in-r/15058684#15058684

**Comment by jread-usgs** [comment]
that was just a "re:docker" comment. I don't really want to see sources

**Comment by lawinslow** [comment]
Here's the bigger issue here really. 

http://programmers.stackexchange.com/questions/80084/is-premature-optimization-really-the-root-of-all-evil

always something to keep in my when you have a working function.

**Comment by jread-usgs** [comment]
Thanks, sport

**Comment by jread-usgs** [comment]
this is going to be in `read_unitted()`
