### ISSUE TITLE
Don't use the `data` function from within a package

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/mda.streams#51]
here: https://github.com/USGS-R/mda.streams/blob/master/R/init_nwis_sites.R#L15

Causes the variable to be exported to the global environment. Similar to issue with dataRetrieval. @ldecicco-USGS do you have a link to your solution in dR?

**Comment by ldecicco-USGS** [comment]
Put the states data in a file called sysdata.rda. You can also export that data.  When it's in the sysdata.rda file, you can just call it:

https://github.com/USGS-R/EGRET/blob/master/R/plotFluxHist.R#L77
here's how to export it (the whole chunk, not just that line):
https://github.com/USGS-R/EGRET/blob/master/R/EGRET.R#L50

If that doesn't make sense, let me know.

Better question, why did you write that site query (for state) and not just tell me there was a simple option in `readNWISdata` that was missing???? All I need to do is allow 'site' as a service argument (in addition to dv, and iv), and you don't need the `get.state.sites` and `get.site.data functions`. If there's ever something you can't get from dataRetrieval that goes to the waterservice or waterdata web services, let me know.

**Comment by ldecicco-USGS** [comment]
I guess Luke asked specifically about the dataRetrieval data. I switched over to `sysdata` on the last update to CRAN. That means that functions that laz-ily call parameterCdFile can be used as Imports to other packages. Same process as EGRET (put data in sysdata instead of the data folder)

**Comment by jread-usgs** [comment]
@ldecicco-USGS I am tackling this today and would like to revisit the above conversation if you are willing

**Comment by ldecicco-USGS** [comment]
sure. `readNWISdata` can do sites now on the latest `dataRetrieval` version. Not sure if you are refactoring those functions, or adding states to sysdata. Either way, let me know what you need.
