### ISSUE TITLE
states is public

### ISSUE THREAD

**Issue by dlorenz-usgs** [USGS-R/mda.streams#52]
The call to data(states) creates the states list in the user environment not just local to the function. The LazyData line in the DESCRIPTION file makes states visible and available to any user. Removing it would still make the data available, but not visible. It is all about promises, which I do not fully understand.
  I still think that having an additional argument to init_nwis_sites would make this function very helpful to all users, not just Powell Center project users. For example, I might be interested in getting all sites in Minnesota that have suspended sediment data. But if you only every want to get data for all states, then I'd suggest renaming it to some name that represent the data but is not likely to be used by another user, say something like states_name_list. Then, in that function, and anywhere else the data are needed, you'd use
states <- get("states_name_list", pos="package:mda.streams")
and you'd be absolutely sure that you got the correct data. By continuing to use stats as the object in the function, you would not need to change any code.

**Comment by ldecicco-USGS** [comment]
I think @lawinslow just opened almost the same thing in #51 

I also just opened an issue in dataRetrieval(https://github.com/USGS-R/dataRetrieval/issues/84) that should do what you are asking in that SS example. The skeleton is basically all there.
