### ISSUE TITLE
where are the units?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#59]
What are the units of each time series, and where is that information stored? Does this package do anything to guarantee that units are accurate at each stage of the downloading/uploading/analysis?

**Comment by jread-usgs** [comment]
They could be in a number of places. Personally, I like the idea of changing the timeseries format like you have as example data in `streamMetabolizer` with units as the second row. Thoughts? Otherwise, they could be in the item metadata, but I fear that is too disconnected w/ the data.

**Comment by aappling-usgs** [comment]
Sure, I think I like the data format of that sample data (first few lines here for the record). 
```
"date.time","DO.obs","DO.deficit","depth","k.O2","light"
NA,"mg L^-1","mg L^-1","m","m d^-1","J m^-2 s^-1"
"date.time","DO.obs","DO.deficit","depth","k.O2","light"
"2012-08-30 00:00:00",7.39,2.67581239853204,1.5,10,0
"2012-08-30 00:05:00",7.39,2.68045357664552,1.5,10,0
```
I don't like the repetition of the column names, but I do like that if you don't want to use `unitted` you just use `read.csv(skip=2)` (to read just the data) and/or also `read.csv(nrow=1)` (to look at the units). 

Maybe it's time to officially support file saving in `unitted` - what do you think? Should I write a couple of functions to write and read data.frames in this format? With or without the first line of repeated header names?

**Comment by jread-usgs** [comment]
I think we are handling this elsewhere and have the logic within mda to cover it.
