### ISSUE TITLE
should get_title be public?

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#63]
Jordan brought this up in comments to PR #62.

So there are site IDs like nwis_234516235, and item IDs like 54fa240ce4b02419550d9f68. get_title converts between the two, but most of what I see on mda.streams operates with site IDs only. So is it the job of mda.streams to abstract away item IDs from the user? Or should the user be able to tap into other sbtools tools by using conversion functions like get_title?

**Comment by jread-usgs** [comment]
I guess it depends on what we want to do with the title, or whether we expect value to come out of it. These titles have some info, but the query functions in sbtools are really the things used to find data and items. 

But, I think it is too convenient of a function to keep it private in the package. I suggest exporting it, even if it is only a handy thing to have around.
