### ISSUE TITLE
make scheme='mda.streams' a variable

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#64]
store character value as package variable, modifiable by user during session

**Comment by jread-usgs** [comment]
:+1:

**Comment by jread-usgs** [comment]
Starting to do this (see #83 ), but we will need to take this throughout for all of the gets and posts etc. might be better to pull out the argument and do a `set_scheme` function, which sets the internal package var, and then we always point to that.

**Comment by aappling-usgs** [comment]
there should already be a set_scheme function. and a get_scheme, too.

On Thu, May 28, 2015 at 3:42 PM, Jordan S Read <notifications@github.com>
wrote:

> Starting to do this (see #83
> <https://github.com/USGS-R/mda.streams/pull/83> ), but we will need to
> take this throughout for all of the gets and posts etc. might be better to
> pull out the argument and do a set_scheme function, which sets the
> internal package var, and then we always point to that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/mda.streams/issues/64#issuecomment-106589918>.
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927

**Comment by jread-usgs** [comment]
ahh - ok, I will use that thanks

**Comment by aappling-usgs** [comment]
thank YOU for pushing it forward! been wanting to get that done for a while.

On Thu, May 28, 2015 at 3:52 PM, Jordan S Read <notifications@github.com>
wrote:

> ahh - ok, I will use that thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/mda.streams/issues/64#issuecomment-106592834>.
>



-- 
Alison Appling
Postdoctoral Fellow, USGS Powell Center
USGS Center for Integrated Data Analytics and University of Wisconsin -
Madison
Phone: (608) 821-3927

**Comment by aappling-usgs** [comment]
done with #86
