### ISSUE TITLE
error/warn on empty init_nwis_sites return list

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/mda.streams#66]
```mda.streams::init_nwis_sites(p_codes=c('00010', '00060', '00095', '00300'), stateCd="VT")```
returns 
```[1] "nwis_"```

**Comment by jread-usgs** [comment]
that's no good ... :-1:

**Comment by aappling-usgs** [comment]
now `stage_nwis_sitelist`. resolved by commit 0ab649f
