### ISSUE TITLE
change structure of "get" and "post" methods in package

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#68]
- get pulls in data and writes a file
 - post takes a local file and POSTs it.

**Comment by jread-usgs** [comment]
related to #67

**Comment by appling** [comment]
might want to pull out an internal function (e.g., write_ts) that converts from df to tsv, does the time stamp and other checking on the way, and is called by get_nldas_df, get_nwis_df, etc.

**Comment by jread-usgs** [comment]
yep, good idea.

**Comment by jread-usgs** [comment]
will be 
`stage_nwis_tsv` and includes a get and a `write_tsv` call
`post_ts` keeps name as-is

**Comment by jread-usgs** [comment]
changing args to `sites` (plural) so we can stage multiple sites at once

**Comment by jread-usgs** [comment]
no longer using a write_ts concept, because we added UTC as unit and no longer need to do anything fancy other than call `write_unitted`
