### ISSUE TITLE
create variable and p-code lookup

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#69]
- [ ] doobs
- [ ] wtr
- [ ] disch
- [ ] stage
- [ ] light/PAR (pcode: 99988)

w/ long names too

**Comment by appling** [comment]
:+1:

**Comment by appling** [comment]
where do non-NWIS data fit? These won't have p codes, but they should have short & long names, and maybe codes specific to other sources.
- [ ] modeled depth
- [ ] depth from bob's undergrad
- [ ] k
- [ ] modeled light
etc.

**Comment by jread-usgs** [comment]
agreed. Need units in this look up too.

**Comment by jread-usgs** [comment]
I will mock something up and we can iterate on the PR

**Comment by jread-usgs** [comment]
can add the other data at any point, as long as the pattern in #74 works
