### ISSUE TITLE
consistent interface between `model_metabolism` and all `metab_model` funs

### ISSUE THREAD

**Issue by appling** [USGS-R/mda.streams#78]
either `metab_model` funs such as `metab_simple` should all accept the same arguments and ignore some, or (preferred, i think) model_metabolism should figure out which arguments need to be sent and make sure that the config says type="none", src=NA for arguments that aren't required for a given model type

**Comment by aappling-usgs** [comment]
close as of #85

**Comment by aappling-usgs** [comment]
finished with #114
