### ISSUE TITLE
agree on time format for flat file tsvs

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#79]
This:
"DateTime"	"ts_doobs"
#""	"units"
2014-01-01 05:00:00	10.6

Isn't going to let us know we are in UTC. ISO8601 is probably too rich/confusing for others to use? Thoughts @aappling-usgs @lawinslow

**Comment by lawinslow** [comment]
Think ISO is too confusing? Hmmm, could do both. "2014-01-01 05:00:00" and "2014-01-01T05:00:00Z"

**Comment by lawinslow** [comment]
I'm not sure if there's a better way to capture time zones, you could add a UTC-offset column or something. Might be more obvious to people

**Comment by appling** [comment]
it wouldn't be horrible to put "UTC" in the units, IMO. then on reading, do as.POSIXct(DateTime, tz=get_units(DateTime))

or tack " -0000" to the end of every date-time string on writing, and use strftime(DateTime, format="%Y-%m-%d %H:%M:%S %z")

**Comment by jread-usgs** [comment]
will be adding "UTC" to units
