### ISSUE TITLE
implement get_var_units()

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#80]
Handles variable name (or p_code?) and dispatches proper lookup method for units

**Comment by jread-usgs** [comment]
if we want the nwis units to come out of dataRetrieval, would need this: https://github.com/USGS-R/dataRetrieval/issues/124

Alternatively, coding them based on p_code in https://github.com/USGS-R/mda.streams/blob/master/R/get_var_codes.R#L27 wouldn't be terrible either

**Comment by aappling-usgs** [comment]
yeah, i like putting them in get_var_codes for now. in the future let's look into using dataRetrieval and making unitted smarter about "a/b2/c" units formats

**Comment by aappling-usgs** [comment]
switching from blocker to enhancement because what we have is good enough for now

**Comment by jread-usgs** [comment]
probably even a wontfix. We won't get things like 'ft^3 s^-1' from a service, so this should probably be where the units are kept

**Comment by aappling-usgs** [comment]
works for me. the units you put in get_var_codes() are definitely right, right?

**Comment by jread-usgs** [comment]
they come from the service (manually) and then need to be translated into `unitted` style syntax, so yes.

**Comment by aappling-usgs** [comment]
added to get_var_codes in #95. still the same idea.

**Comment by appling** [comment]
i'm thinking wontfix because i like how get_var_codes() is doing it already. if anybody disagrees, speak now.
