### ISSUE TITLE
post_ts will gzip, get_ts will unzip

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#81]

**Comment by jread-usgs** [comment]
changing this again. Sorry. post will post the simple file returned from `stage_var_ts`, which will now handle the gzipping because that can happen within `write_unitted`. Sorry for confusion!

**Comment by appling** [comment]
awesome! can we also read straight from a compressed file?

**Comment by jread-usgs** [comment]
I think so - I will give you a shout out in the next PR for it

**Comment by jread-usgs** [comment]
but one thing that would be nice for write_unitted is to do `write_unitted(x, file, ...)` since file is a first class citizen. I found myself doing `write_unitted(x, 'stuff.tsv')` and wondering why it printed to screen. (`write_unitted(x, file = 'stuff.tsv')`works of course...)

**Comment by appling** [comment]
good idea! just committed that change.

**Comment by jread-usgs** [comment]
This is `post_ts`, `write_ts`, `download_ts` and `read_ts`. PR on the way.

**Comment by aappling-usgs** [comment]
post, write, download, and read ts are all implemented
