### ISSUE TITLE
improve error checking in write_ts

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/mda.streams#84]
data has two columns
first column as "UTC" units
second column has same name as variable (or ts_name, whichever it is)

**Comment by jread-usgs** [comment]
probably should do the same test on the output of `read_ts`? @aappling-usgs ?

**Comment by aappling-usgs** [comment]
yeah, sounds good.

**Comment by jread-usgs** [comment]
@aappling-usgs can we close this one?

**Comment by aappling-usgs** [comment]
absolutely!
