### ISSUE TITLE
list_datasets needs checking/fixing

### ISSUE THREAD

**Issue by appling** [USGS-R/mda.streams#94]
after the switch to var_src, this function will need a revamp.

**Comment by aappling-usgs** [comment]
also make sure the documentation adequately explains how this function handles ts versus watershed versus other data types

**Comment by aappling-usgs** [comment]
make sure you can leave out site (as the documentation says) or that hte documentation explains that you need to supply a site (as the code currently implies). just be consistent.

**Comment by jread-usgs** [comment]
working on this now.

**Comment by aappling-usgs** [comment]
when some sites have a dataset and others don't, the current code gives an error. the following lines produce this error when some sites have doobs and others have nothing, e.g., an intermediate state in test-stage.R.

```
> set_scheme("mda_streams_dev")
> list_datasets(sites)

 Error in rowSums(.) : 'x' must be an array of at least two dimensions 
11 stop("'x' must be an array of at least two dimensions") 
10 rowSums(.) 
9 function_list[[k]](value) 
8 withVisible(function_list[[k]](value)) 
7 freduce(value, `_function_list`) 
6 `_fseq`(`_lhs`) 
5 eval(expr, envir, enclos) 
4 eval(quote(`_fseq`(`_lhs`)), env, env) 
3 withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2 sapply(str_match_patterns, function(x) str_detect(var_names, 
    pattern = x)) %>% rowSums() at list_datasets.R#37
1 list_datasets(sites) 
```

**Comment by jread-usgs** [comment]
I will look into this

**Comment by aappling-usgs** [comment]
thanks

**Comment by jread-usgs** [comment]
not sure how we should expect this to work. I thought this was a site-specific function, so passing it multiple sites probably results in a case I didn't code for. Should I check and verify that `site_names` is length == 1?

note from docs:
```R
#' @param site_name a character vector of length one with a site name such 
#'   as those returned from make_site_name()
```

**Comment by jread-usgs** [comment]
But also, I wasn't able to reproduce:

```R
set_scheme("mda_streams_dev")
sites <- list_sites()
list_datasets(sites)
[1] "ts_doobs_nwis"
```

**Comment by appling** [comment]
that would be fine. i'd been experimenting with using it for several sites
(didn't read the doc), but it's not very useful that way, anyway.

On Tue, Jun 16, 2015 at 4:07 PM, Jordan S Read <notifications@github.com>
wrote:

> not sure how we should expect this to work. I thought this was a
> site-specific function, so passing it multiple sites probably results in a
> case I didn't code for. Should I check and verify that site_names is
> length == 1?
>
> note from docs:
>
> #' @param site_name a character vector of length one with a site name such #'   as those returned from make_site_name()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/mda.streams/issues/94#issuecomment-112570145>.
>



-- 
Alison Appling
Cell: (919) 964-0196

**Comment by jread-usgs** [comment]
Ok, I wasn't really sure what use-case that would cover (multiple sites), because we have get_var_codes()

**Comment by aappling-usgs** [comment]
yeah, fair enough. now that i'm working with many sites at a time i'm wanting summary functions to tell me what's available, but there's probably another function yet to be written that should tell us that. let's leave list_datasets() as it is (i'll add a check for length(site_name) == 1)

**Comment by aappling-usgs** [comment]
i can't reproduce it at the moment, either. i wonder if it had to do with sites with incompletely posted ts items (i'm making a lot of those today)

**Comment by jread-usgs** [comment]
thanks.

**Comment by aappling-usgs** [comment]
`list_datasets` currently does everything we need. calling it good for now.
